version: '2'
#定义服务lrnp(openresty1.13+redis3.2.9+php7.1.12) 和 mysql(mysql5.7) + shadowsocks服务
services:
        #服务名称
        lrnp:
            #依赖mysql服务，意味着在启动lrnp之前先启动mysql服务容器
            depends_on:
               - mysql
            #nginx镜像的路径
            #image: docker.io/wuyuzai/mydockeros:lrnp
            #aliyun镜像地址
            image: registry.cn-hangzhou.aliyuncs.com/webss/lrnp
            #映射文件/文件夹到宿主机，持久化和方便管理
            # volumes格式, 本地文件地址:容器内文件地址
            volumes:
                - /root/docker/web:/opt/openresty/nginx/html
                - /root/docker/logs/nginx_log:/opt/openresty/nginx/logs
                - /root/docker/nginx-conf:/opt/openresty/nginx/conf
                - /root/docker/logs/php_log:/tmp/phplogs
                - /root/docker/php/php.ini:/etc/php/php.ini
                - /root/docker/php/www.conf:/usr/local/php/etc/php-fpm.d/www.conf
                - /root/docker/redis/redis.conf:/etc/redis.conf
                - /root/docker/logs/redis_log:/tmp/redislogs
            #openresty服务意外退出时自动重启
            restart: always
            #docker中ulimit设置
            ulimits:
                nproc: 102400
                nofile:
                    soft: 102400
                    hard: 102400
            networks:
                - webserver
            #网络模式HOST(使用宿主机网络) 性能更优
            #network_mode: host
            ports:
                - 80:80
                - 443:443
                #- 6379:6379
            hostname: lrnp7
            #容器名称
            container_name: lrnp7   
        #服务名称
        mysql:
            #image: docker.io/mysql:5.7
            #阿里云镜像地址
            image: registry.cn-hangzhou.aliyuncs.com/webss/mysql:5.7
            #设置MYSQL_ROOT_PASSWORD环境变量，这里是设置mysql的root密码。
            environment:
                MYSQL_ROOT_PASSWORD: zz520ll
            #映射文件路径
            volumes:
                - /root/docker/mysqld/config:/etc/mysql
                - /root/docker/mysqld/mysqldata:/var/lib/mysql
                - /root/docker/logs/mysql_log:/var/log/mysql
            #mysql服务意外退出时自动重启
            restart: always
            #docker中ulimit设置
            ulimits:
                nproc: 102400
                nofile:
                    soft: 102400
                    hard: 102400
            networks:
                - webserver
            #网络模式HOST 性能更优
            #network_mode: host
            #ports:
                #- 3306:3306
            hostname: mysql57
            #容器名称
            container_name: mysql57
#定义docker全局网络服务
networks:
        webserver:
            driver: bridge
