version: '2'
services:
        shadowsocks:
            #image: docker.io/easypi/shadowsocks-libev
            image: registry.cn-hangzhou.aliyuncs.com/webss/ss-server
            #网络模式HOST
            #network_mode: host
            ports:
                - 7879:7879
            environment:
                SERVER_ADDR: 0.0.0.0
                PASSWORD: www.baidu.com
                SERVER_PORT: 7879
            restart: always
            #容器名称
            container_name: shadowsocks
